export const surpriseMePrompts = [
  "un estampado cuadrado con patrones de ajedrez en blanco y negro",
  "un diseño cuadrado geométrico con líneas y formas abstractas",
  "un patrón cuadrado con elementos urbanos y rascacielos",
  "un estampado cuadrado con ilustraciones de animales en estilo ilustrativo",
  "un diseño cuadrado con elementos tecnológicos y circuitos electrónicos",
  "un patrón cuadrado con formas abstractas en colores metálicos",
  "un estampado cuadrado con elementos botánicos y hojas de palmera",
  "un diseño cuadrado con motivos tribales en colores tierra",
  "un patrón cuadrado inspirado en la arquitectura moderna",
  "un estampado cuadrado con figuras geométricas en colores pastel",
  "un diseño cuadrado con ilustraciones de frutas tropicales",
  "un patrón cuadrado con elementos retro y nostálgicos",
  "un estampado cuadrado con motivos cósmicos y estrellas",
  "un diseño cuadrado con letras y palabras inspiradoras",
  "un patrón cuadrado inspirado en el arte urbano y los grafitis",
  "un estampado cuadrado con ilustraciones de animales en estilo acuarela",
  "un diseño cuadrado con elementos vintage y detalles en sepia",
  "un patrón cuadrado con formas abstractas en colores brillantes",
  "un patrón circular con flores de colores vibrantes",
  "un diseño circular geométrico en tonos pastel",
  "un estampado circular con mandalas en blanco y negro",
  "un diseño circular con elementos tropicales y palmeras",
  "un patrón circular inspirado en el arte pop de los años 60",
  "un estampado circular con motivos de animales en estilo acuarela",
  "un diseño circular con elementos cósmicos y galaxias",
  "un patrón circular con formas abstractas en colores neón",
  "un estampado circular con elementos marinos como conchas y estrellas de mar",
  "un diseño circular con símbolos tribales en tonos tierra",
  "un patrón circular con ilustraciones de frutas jugosas",
  "un estampado circular con motivos étnicos y geométricos en colores vivos",
  "un diseño circular con letras y tipografías creativas",
  "un patrón circular inspirado en la naturaleza con hojas y flores",
  "un estampado circular con elementos futuristas y líneas abstractas",
  "un diseño circular con ilustraciones de animales salvajes",
  "un patrón circular con motivos vintage y elementos retro",
  "un estampado circular con figuras geométricas en colores contrastantes",
  "un diseño circular con elementos botánicos y plantas exóticas",
  "Un estampado cuadrado con ilustraciones de instrumentos musicales en estilo vintage",
  "Un diseño cuadrado con elementos de la cultura oriental y símbolos en tonos dorados",
  "Un patrón cuadrado con formas abstractas en tonos pastel y elementos florales",
  "Un estampado cuadrado con motivos de animales marinos en estilo acuarela",
  "Un diseño cuadrado con elementos de la ciudad y la cultura urbana en tonos oscuros",
  "Un patrón cuadrado inspirado en la arquitectura clásica y monumentos históricos",
  "Un estampado cuadrado con ilustraciones de objetos vintage en estilo retro",
  "Un diseño cuadrado con elementos de la naturaleza y paisajes en colores verdes y azules",
  "Un patrón cuadrado con formas geométricas en colores brillantes y llamativos",
  "Un estampado cuadrado con motivos de animales salvajes en estilo tribal",
  "Un diseño cuadrado con elementos de la cultura pop y el arte callejero en tonos llamativos",
  "Un patrón cuadrado inspirado en la moda y la alta costura en colores pastel y metálicos",
  "Un estampado cuadrado con ilustraciones de insectos en estilo detallado",
  "Un diseño cuadrado con elementos de la cultura africana y símbolos tribales en tonos tierra",
  "Un patrón cuadrado con formas abstractas en colores oscuros y elementos de la noche",
  "Un estampado cuadrado con motivos de la vida marina en estilo acuarela y colores brillantes",
  "Un diseño cuadrado con elementos de la cultura latinoamericana y símbolos en tonos cálidos",
  "Un patrón cuadrado inspirado en la geometría sagrada y los símbolos espirituales en tonos dorados",
  "Un estampado cuadrado con ilustraciones de aves en estilo naturalista",
  "Un diseño cuadrado con elementos de la cultura japonesa y símbolos en tonos rojos y negros",
  "Un patrón circular con elementos abstractos en tonos fríos y metalizados",
  "Un diseño circular con motivos florales y elementos de la naturaleza en tonos cálidos",
  "Un estampado circular con ilustraciones de insectos en estilo detallado y colores vibrantes",
  "Un diseño circular con elementos de la cultura egipcia y símbolos en tonos dorados",
  "Un patrón circular inspirado en el universo y la astrología en colores oscuros y nebulosos",
  "Un estampado circular con motivos de la vida salvaje en estilo acuarela y colores brillantes",
  "Un diseño circular con elementos de la cultura hindú y símbolos en tonos brillantes",
  "Un patrón circular con formas geométricas en colores vibrantes y contrastantes",
  "Un estampado circular con ilustraciones de plantas y flores en estilo naturalista y colores pastel",
  "Un diseño circular con elementos de la cultura azteca y símbolos en tonos terracota",
];
