export const surpriseMePrompts = [

  'un estampado cuadrado con patrones de ajedrez en blanco y negro',
  'un diseño cuadrado geométrico con líneas y formas abstractas',
  'un patrón cuadrado con elementos urbanos y rascacielos',
  'un estampado cuadrado con ilustraciones de animales en estilo ilustrativo',
  'un diseño cuadrado con elementos tecnológicos y circuitos electrónicos',
  'un patrón cuadrado con formas abstractas en colores metálicos',
  'un estampado cuadrado con elementos botánicos y hojas de palmera',
  'un diseño cuadrado con motivos tribales en colores tierra',
  'un patrón cuadrado inspirado en la arquitectura moderna',
  'un estampado cuadrado con figuras geométricas en colores pastel',
  'un diseño cuadrado con ilustraciones de frutas tropicales',
  'un patrón cuadrado con elementos retro y nostálgicos',
  'un estampado cuadrado con motivos cósmicos y estrellas',
  'un diseño cuadrado con letras y palabras inspiradoras',
  'un patrón cuadrado inspirado en el arte urbano y los grafitis',
  'un estampado cuadrado con ilustraciones de animales en estilo acuarela',
  'un diseño cuadrado con elementos vintage y detalles en sepia',
  'un patrón cuadrado con formas abstractas en colores brillantes',
  'un patrón circular con flores de colores vibrantes',
  'un diseño circular geométrico en tonos pastel',
  'un estampado circular con mandalas en blanco y negro',
  'un diseño circular con elementos tropicales y palmeras',
  'un patrón circular inspirado en el arte pop de los años 60',
  'un estampado circular con motivos de animales en estilo acuarela',
  'un diseño circular con elementos cósmicos y galaxias',
  'un patrón circular con formas abstractas en colores neón',
  'un estampado circular con elementos marinos como conchas y estrellas de mar',
  'un diseño circular con símbolos tribales en tonos tierra',
  'un patrón circular con ilustraciones de frutas jugosas',
  'un estampado circular con motivos étnicos y geométricos en colores vivos',
  'un diseño circular con letras y tipografías creativas',
  'un patrón circular inspirado en la naturaleza con hojas y flores',
  'un estampado circular con elementos futuristas y líneas abstractas',
  'un diseño circular con ilustraciones de animales salvajes',
  'un patrón circular con motivos vintage y elementos retro',
  'un estampado circular con figuras geométricas en colores contrastantes',
  'un diseño circular con elementos botánicos y plantas exóticas'

];